<?xml version="1.0" encoding="utf-8"?>
<AddOnRegData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" SlientInstallation="No" SlientUpgrade="No" Partnernmsp="Star" SchemaVersion="3.0" Type="" MultipleVersion="false" OnDemand="" OnPremise="" ExtName="SBOAddonProject1.0.1" ExtVersion="1.0.1" Contdata="" Partner="Star Technology" DBType="HANA" ClientType="A">
  <Validity>
    <SBOCompatibility>
      <Version From="" To="" />
    </SBOCompatibility>
  </Validity>
  <Configuration>
    <Repository>
      <Properties />
    </Repository>
    <Deployment>
      <Properties />
    </Deployment>
    <Assignment>
      <Properties />
    </Assignment>
  </Configuration>
  <Addons>
    <Addon Name="" Group="" ForceFlag="" Visible="" AutoAssign="" SelfUpgrd="">
      <x86 AddonExe="" AddonSig="" AddonSigSha256="">
        <Installation>
          <Files />
        </Installation>
        <Uninstallation>
          <Files />
        </Uninstallation>
      </x86>
      <x64 AddonExe="" AddonSig="" AddonSigSha256="">
        <Installation>
          <Files />
        </Installation>
        <Uninstallation>
          <Files />
        </Uninstallation>
      </x64>
    </Addon>
  </Addons>
  <XApps>
    <XApp Name="" Path="" FileName="" />
  </XApps>
  <UDQs>
    <UDQ udqname="">
      <Hana FileName="" />
    </UDQ>
  </UDQs>
</AddOnRegData>