//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBOAddonProject1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CmpAuthRequest", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class CmpAuthRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        private long CuitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long Cuit {
            get {
                return this.CuitField;
            }
            set {
                if ((this.CuitField.Equals(value) != true)) {
                    this.CuitField = value;
                    this.RaisePropertyChanged("Cuit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacModTipoResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class FacModTipoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.FacModTipo[] ResultGetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Err[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Evt[] EventsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SBOAddonProject1.ServiceReference1.FacModTipo[] ResultGet {
            get {
                return this.ResultGetField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultGetField, value) != true)) {
                    this.ResultGetField = value;
                    this.RaisePropertyChanged("ResultGet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SBOAddonProject1.ServiceReference1.Err[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SBOAddonProject1.ServiceReference1.Evt[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacModTipo", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class FacModTipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FchDesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FchHastaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cod {
            get {
                return this.CodField;
            }
            set {
                if ((object.ReferenceEquals(this.CodField, value) != true)) {
                    this.CodField = value;
                    this.RaisePropertyChanged("Cod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FchDesde {
            get {
                return this.FchDesdeField;
            }
            set {
                if ((object.ReferenceEquals(this.FchDesdeField, value) != true)) {
                    this.FchDesdeField = value;
                    this.RaisePropertyChanged("FchDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FchHasta {
            get {
                return this.FchHastaField;
            }
            set {
                if ((object.ReferenceEquals(this.FchHastaField, value) != true)) {
                    this.FchHastaField = value;
                    this.RaisePropertyChanged("FchHasta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Err", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class Err : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evt", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class Evt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CbteTipoResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class CbteTipoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.CbteTipo[] ResultGetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Err[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Evt[] EventsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SBOAddonProject1.ServiceReference1.CbteTipo[] ResultGet {
            get {
                return this.ResultGetField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultGetField, value) != true)) {
                    this.ResultGetField = value;
                    this.RaisePropertyChanged("ResultGet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SBOAddonProject1.ServiceReference1.Err[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SBOAddonProject1.ServiceReference1.Evt[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CbteTipo", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class CbteTipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocTipoResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class DocTipoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.DocTipo[] ResultGetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Err[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Evt[] EventsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SBOAddonProject1.ServiceReference1.DocTipo[] ResultGet {
            get {
                return this.ResultGetField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultGetField, value) != true)) {
                    this.ResultGetField = value;
                    this.RaisePropertyChanged("ResultGet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SBOAddonProject1.ServiceReference1.Err[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SBOAddonProject1.ServiceReference1.Evt[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocTipo", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class DocTipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpcionalTipoResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class OpcionalTipoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.OpcionalTipo[] ResultGetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Err[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Evt[] EventsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SBOAddonProject1.ServiceReference1.OpcionalTipo[] ResultGet {
            get {
                return this.ResultGetField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultGetField, value) != true)) {
                    this.ResultGetField = value;
                    this.RaisePropertyChanged("ResultGet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SBOAddonProject1.ServiceReference1.Err[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SBOAddonProject1.ServiceReference1.Evt[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpcionalTipo", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class OpcionalTipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CmpDatos", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class CmpDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CbteModoField;
        
        private long CuitEmisorField;
        
        private int PtoVtaField;
        
        private int CbteTipoField;
        
        private long CbteNroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CbteFchField;
        
        private double ImpTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodAutorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocTipoReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNroReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Opcional[] OpcionalesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CbteModo {
            get {
                return this.CbteModoField;
            }
            set {
                if ((object.ReferenceEquals(this.CbteModoField, value) != true)) {
                    this.CbteModoField = value;
                    this.RaisePropertyChanged("CbteModo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long CuitEmisor {
            get {
                return this.CuitEmisorField;
            }
            set {
                if ((this.CuitEmisorField.Equals(value) != true)) {
                    this.CuitEmisorField = value;
                    this.RaisePropertyChanged("CuitEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PtoVta {
            get {
                return this.PtoVtaField;
            }
            set {
                if ((this.PtoVtaField.Equals(value) != true)) {
                    this.PtoVtaField = value;
                    this.RaisePropertyChanged("PtoVta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CbteTipo {
            get {
                return this.CbteTipoField;
            }
            set {
                if ((this.CbteTipoField.Equals(value) != true)) {
                    this.CbteTipoField = value;
                    this.RaisePropertyChanged("CbteTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long CbteNro {
            get {
                return this.CbteNroField;
            }
            set {
                if ((this.CbteNroField.Equals(value) != true)) {
                    this.CbteNroField = value;
                    this.RaisePropertyChanged("CbteNro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CbteFch {
            get {
                return this.CbteFchField;
            }
            set {
                if ((object.ReferenceEquals(this.CbteFchField, value) != true)) {
                    this.CbteFchField = value;
                    this.RaisePropertyChanged("CbteFch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double ImpTotal {
            get {
                return this.ImpTotalField;
            }
            set {
                if ((this.ImpTotalField.Equals(value) != true)) {
                    this.ImpTotalField = value;
                    this.RaisePropertyChanged("ImpTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CodAutorizacion {
            get {
                return this.CodAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodAutorizacionField, value) != true)) {
                    this.CodAutorizacionField = value;
                    this.RaisePropertyChanged("CodAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DocTipoReceptor {
            get {
                return this.DocTipoReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.DocTipoReceptorField, value) != true)) {
                    this.DocTipoReceptorField = value;
                    this.RaisePropertyChanged("DocTipoReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string DocNroReceptor {
            get {
                return this.DocNroReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNroReceptorField, value) != true)) {
                    this.DocNroReceptorField = value;
                    this.RaisePropertyChanged("DocNroReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public SBOAddonProject1.ServiceReference1.Opcional[] Opcionales {
            get {
                return this.OpcionalesField;
            }
            set {
                if ((object.ReferenceEquals(this.OpcionalesField, value) != true)) {
                    this.OpcionalesField = value;
                    this.RaisePropertyChanged("Opcionales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Opcional", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class Opcional : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CmpResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class CmpResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.CmpDatos CmpRespField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Obs[] ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FchProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Evt[] EventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SBOAddonProject1.ServiceReference1.Err[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SBOAddonProject1.ServiceReference1.CmpDatos CmpResp {
            get {
                return this.CmpRespField;
            }
            set {
                if ((object.ReferenceEquals(this.CmpRespField, value) != true)) {
                    this.CmpRespField = value;
                    this.RaisePropertyChanged("CmpResp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SBOAddonProject1.ServiceReference1.Obs[] Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FchProceso {
            get {
                return this.FchProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.FchProcesoField, value) != true)) {
                    this.FchProcesoField = value;
                    this.RaisePropertyChanged("FchProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SBOAddonProject1.ServiceReference1.Evt[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SBOAddonProject1.ServiceReference1.Err[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Obs", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class Obs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DummyResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    [System.SerializableAttribute()]
    public partial class DummyResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DbServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthServerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AppServer {
            get {
                return this.AppServerField;
            }
            set {
                if ((object.ReferenceEquals(this.AppServerField, value) != true)) {
                    this.AppServerField = value;
                    this.RaisePropertyChanged("AppServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DbServer {
            get {
                return this.DbServerField;
            }
            set {
                if ((object.ReferenceEquals(this.DbServerField, value) != true)) {
                    this.DbServerField = value;
                    this.RaisePropertyChanged("DbServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AuthServer {
            get {
                return this.AuthServerField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthServerField, value) != true)) {
                    this.AuthServerField = value;
                    this.RaisePropertyChanged("AuthServer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/", ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name Auth from namespace http://servicios1.afip.gob.ar/wscdc/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/ComprobantesModalidadConsultar", ReplyAction="*")]
        SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarResponse ComprobantesModalidadConsultar(SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/ComprobantesModalidadConsultar", ReplyAction="*")]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarResponse> ComprobantesModalidadConsultarAsync(SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequest request);
        
        // CODEGEN: Generating message contract since element name Auth from namespace http://servicios1.afip.gob.ar/wscdc/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/ComprobantesTipoConsultar", ReplyAction="*")]
        SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarResponse ComprobantesTipoConsultar(SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/ComprobantesTipoConsultar", ReplyAction="*")]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarResponse> ComprobantesTipoConsultarAsync(SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequest request);
        
        // CODEGEN: Generating message contract since element name Auth from namespace http://servicios1.afip.gob.ar/wscdc/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/DocumentosTipoConsultar", ReplyAction="*")]
        SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarResponse DocumentosTipoConsultar(SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/DocumentosTipoConsultar", ReplyAction="*")]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarResponse> DocumentosTipoConsultarAsync(SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequest request);
        
        // CODEGEN: Generating message contract since element name Auth from namespace http://servicios1.afip.gob.ar/wscdc/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/OpcionalesTipoConsultar", ReplyAction="*")]
        SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarResponse OpcionalesTipoConsultar(SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/OpcionalesTipoConsultar", ReplyAction="*")]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarResponse> OpcionalesTipoConsultarAsync(SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequest request);
        
        // CODEGEN: Generating message contract since element name Auth from namespace http://servicios1.afip.gob.ar/wscdc/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/ComprobanteConstatar", ReplyAction="*")]
        SBOAddonProject1.ServiceReference1.ComprobanteConstatarResponse ComprobanteConstatar(SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/ComprobanteConstatar", ReplyAction="*")]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobanteConstatarResponse> ComprobanteConstatarAsync(SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequest request);
        
        // CODEGEN: Generating message contract since element name ComprobanteDummyResult from namespace http://servicios1.afip.gob.ar/wscdc/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/ComprobanteDummy", ReplyAction="*")]
        SBOAddonProject1.ServiceReference1.ComprobanteDummyResponse ComprobanteDummy(SBOAddonProject1.ServiceReference1.ComprobanteDummyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios1.afip.gob.ar/wscdc/ComprobanteDummy", ReplyAction="*")]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobanteDummyResponse> ComprobanteDummyAsync(SBOAddonProject1.ServiceReference1.ComprobanteDummyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobantesModalidadConsultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobantesModalidadConsultar", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequestBody Body;
        
        public ComprobantesModalidadConsultarRequest() {
        }
        
        public ComprobantesModalidadConsultarRequest(SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class ComprobantesModalidadConsultarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth;
        
        public ComprobantesModalidadConsultarRequestBody() {
        }
        
        public ComprobantesModalidadConsultarRequestBody(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            this.Auth = Auth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobantesModalidadConsultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobantesModalidadConsultarResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarResponseBody Body;
        
        public ComprobantesModalidadConsultarResponse() {
        }
        
        public ComprobantesModalidadConsultarResponse(SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class ComprobantesModalidadConsultarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SBOAddonProject1.ServiceReference1.FacModTipoResponse ComprobantesModalidadConsultarResult;
        
        public ComprobantesModalidadConsultarResponseBody() {
        }
        
        public ComprobantesModalidadConsultarResponseBody(SBOAddonProject1.ServiceReference1.FacModTipoResponse ComprobantesModalidadConsultarResult) {
            this.ComprobantesModalidadConsultarResult = ComprobantesModalidadConsultarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobantesTipoConsultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobantesTipoConsultar", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequestBody Body;
        
        public ComprobantesTipoConsultarRequest() {
        }
        
        public ComprobantesTipoConsultarRequest(SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class ComprobantesTipoConsultarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth;
        
        public ComprobantesTipoConsultarRequestBody() {
        }
        
        public ComprobantesTipoConsultarRequestBody(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            this.Auth = Auth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobantesTipoConsultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobantesTipoConsultarResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarResponseBody Body;
        
        public ComprobantesTipoConsultarResponse() {
        }
        
        public ComprobantesTipoConsultarResponse(SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class ComprobantesTipoConsultarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SBOAddonProject1.ServiceReference1.CbteTipoResponse ComprobantesTipoConsultarResult;
        
        public ComprobantesTipoConsultarResponseBody() {
        }
        
        public ComprobantesTipoConsultarResponseBody(SBOAddonProject1.ServiceReference1.CbteTipoResponse ComprobantesTipoConsultarResult) {
            this.ComprobantesTipoConsultarResult = ComprobantesTipoConsultarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentosTipoConsultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocumentosTipoConsultar", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequestBody Body;
        
        public DocumentosTipoConsultarRequest() {
        }
        
        public DocumentosTipoConsultarRequest(SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class DocumentosTipoConsultarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth;
        
        public DocumentosTipoConsultarRequestBody() {
        }
        
        public DocumentosTipoConsultarRequestBody(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            this.Auth = Auth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentosTipoConsultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocumentosTipoConsultarResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarResponseBody Body;
        
        public DocumentosTipoConsultarResponse() {
        }
        
        public DocumentosTipoConsultarResponse(SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class DocumentosTipoConsultarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SBOAddonProject1.ServiceReference1.DocTipoResponse DocumentosTipoConsultarResult;
        
        public DocumentosTipoConsultarResponseBody() {
        }
        
        public DocumentosTipoConsultarResponseBody(SBOAddonProject1.ServiceReference1.DocTipoResponse DocumentosTipoConsultarResult) {
            this.DocumentosTipoConsultarResult = DocumentosTipoConsultarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpcionalesTipoConsultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpcionalesTipoConsultar", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequestBody Body;
        
        public OpcionalesTipoConsultarRequest() {
        }
        
        public OpcionalesTipoConsultarRequest(SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class OpcionalesTipoConsultarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth;
        
        public OpcionalesTipoConsultarRequestBody() {
        }
        
        public OpcionalesTipoConsultarRequestBody(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            this.Auth = Auth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpcionalesTipoConsultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpcionalesTipoConsultarResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarResponseBody Body;
        
        public OpcionalesTipoConsultarResponse() {
        }
        
        public OpcionalesTipoConsultarResponse(SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class OpcionalesTipoConsultarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SBOAddonProject1.ServiceReference1.OpcionalTipoResponse OpcionalesTipoConsultarResult;
        
        public OpcionalesTipoConsultarResponseBody() {
        }
        
        public OpcionalesTipoConsultarResponseBody(SBOAddonProject1.ServiceReference1.OpcionalTipoResponse OpcionalesTipoConsultarResult) {
            this.OpcionalesTipoConsultarResult = OpcionalesTipoConsultarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobanteConstatarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobanteConstatar", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequestBody Body;
        
        public ComprobanteConstatarRequest() {
        }
        
        public ComprobanteConstatarRequest(SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class ComprobanteConstatarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SBOAddonProject1.ServiceReference1.CmpDatos CmpReq;
        
        public ComprobanteConstatarRequestBody() {
        }
        
        public ComprobanteConstatarRequestBody(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth, SBOAddonProject1.ServiceReference1.CmpDatos CmpReq) {
            this.Auth = Auth;
            this.CmpReq = CmpReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobanteConstatarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobanteConstatarResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.ComprobanteConstatarResponseBody Body;
        
        public ComprobanteConstatarResponse() {
        }
        
        public ComprobanteConstatarResponse(SBOAddonProject1.ServiceReference1.ComprobanteConstatarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class ComprobanteConstatarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SBOAddonProject1.ServiceReference1.CmpResponse ComprobanteConstatarResult;
        
        public ComprobanteConstatarResponseBody() {
        }
        
        public ComprobanteConstatarResponseBody(SBOAddonProject1.ServiceReference1.CmpResponse ComprobanteConstatarResult) {
            this.ComprobanteConstatarResult = ComprobanteConstatarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobanteDummyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobanteDummy", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.ComprobanteDummyRequestBody Body;
        
        public ComprobanteDummyRequest() {
        }
        
        public ComprobanteDummyRequest(SBOAddonProject1.ServiceReference1.ComprobanteDummyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ComprobanteDummyRequestBody {
        
        public ComprobanteDummyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobanteDummyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobanteDummyResponse", Namespace="http://servicios1.afip.gob.ar/wscdc/", Order=0)]
        public SBOAddonProject1.ServiceReference1.ComprobanteDummyResponseBody Body;
        
        public ComprobanteDummyResponse() {
        }
        
        public ComprobanteDummyResponse(SBOAddonProject1.ServiceReference1.ComprobanteDummyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class ComprobanteDummyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SBOAddonProject1.ServiceReference1.DummyResponse ComprobanteDummyResult;
        
        public ComprobanteDummyResponseBody() {
        }
        
        public ComprobanteDummyResponseBody(SBOAddonProject1.ServiceReference1.DummyResponse ComprobanteDummyResult) {
            this.ComprobanteDummyResult = ComprobanteDummyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SBOAddonProject1.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SBOAddonProject1.ServiceReference1.ServiceSoap>, SBOAddonProject1.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarResponse SBOAddonProject1.ServiceReference1.ServiceSoap.ComprobantesModalidadConsultar(SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequest request) {
            return base.Channel.ComprobantesModalidadConsultar(request);
        }
        
        public SBOAddonProject1.ServiceReference1.FacModTipoResponse ComprobantesModalidadConsultar(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequest inValue = new SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequestBody();
            inValue.Body.Auth = Auth;
            SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarResponse retVal = ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).ComprobantesModalidadConsultar(inValue);
            return retVal.Body.ComprobantesModalidadConsultarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarResponse> SBOAddonProject1.ServiceReference1.ServiceSoap.ComprobantesModalidadConsultarAsync(SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequest request) {
            return base.Channel.ComprobantesModalidadConsultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarResponse> ComprobantesModalidadConsultarAsync(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequest inValue = new SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.ComprobantesModalidadConsultarRequestBody();
            inValue.Body.Auth = Auth;
            return ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).ComprobantesModalidadConsultarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarResponse SBOAddonProject1.ServiceReference1.ServiceSoap.ComprobantesTipoConsultar(SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequest request) {
            return base.Channel.ComprobantesTipoConsultar(request);
        }
        
        public SBOAddonProject1.ServiceReference1.CbteTipoResponse ComprobantesTipoConsultar(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequest inValue = new SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequestBody();
            inValue.Body.Auth = Auth;
            SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarResponse retVal = ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).ComprobantesTipoConsultar(inValue);
            return retVal.Body.ComprobantesTipoConsultarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarResponse> SBOAddonProject1.ServiceReference1.ServiceSoap.ComprobantesTipoConsultarAsync(SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequest request) {
            return base.Channel.ComprobantesTipoConsultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarResponse> ComprobantesTipoConsultarAsync(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequest inValue = new SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.ComprobantesTipoConsultarRequestBody();
            inValue.Body.Auth = Auth;
            return ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).ComprobantesTipoConsultarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarResponse SBOAddonProject1.ServiceReference1.ServiceSoap.DocumentosTipoConsultar(SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequest request) {
            return base.Channel.DocumentosTipoConsultar(request);
        }
        
        public SBOAddonProject1.ServiceReference1.DocTipoResponse DocumentosTipoConsultar(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequest inValue = new SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequestBody();
            inValue.Body.Auth = Auth;
            SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarResponse retVal = ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).DocumentosTipoConsultar(inValue);
            return retVal.Body.DocumentosTipoConsultarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarResponse> SBOAddonProject1.ServiceReference1.ServiceSoap.DocumentosTipoConsultarAsync(SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequest request) {
            return base.Channel.DocumentosTipoConsultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarResponse> DocumentosTipoConsultarAsync(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequest inValue = new SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.DocumentosTipoConsultarRequestBody();
            inValue.Body.Auth = Auth;
            return ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).DocumentosTipoConsultarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarResponse SBOAddonProject1.ServiceReference1.ServiceSoap.OpcionalesTipoConsultar(SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequest request) {
            return base.Channel.OpcionalesTipoConsultar(request);
        }
        
        public SBOAddonProject1.ServiceReference1.OpcionalTipoResponse OpcionalesTipoConsultar(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequest inValue = new SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequestBody();
            inValue.Body.Auth = Auth;
            SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarResponse retVal = ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).OpcionalesTipoConsultar(inValue);
            return retVal.Body.OpcionalesTipoConsultarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarResponse> SBOAddonProject1.ServiceReference1.ServiceSoap.OpcionalesTipoConsultarAsync(SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequest request) {
            return base.Channel.OpcionalesTipoConsultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarResponse> OpcionalesTipoConsultarAsync(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth) {
            SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequest inValue = new SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.OpcionalesTipoConsultarRequestBody();
            inValue.Body.Auth = Auth;
            return ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).OpcionalesTipoConsultarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SBOAddonProject1.ServiceReference1.ComprobanteConstatarResponse SBOAddonProject1.ServiceReference1.ServiceSoap.ComprobanteConstatar(SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequest request) {
            return base.Channel.ComprobanteConstatar(request);
        }
        
        public SBOAddonProject1.ServiceReference1.CmpResponse ComprobanteConstatar(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth, SBOAddonProject1.ServiceReference1.CmpDatos CmpReq) {
            SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequest inValue = new SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequestBody();
            inValue.Body.Auth = Auth;
            inValue.Body.CmpReq = CmpReq;
            SBOAddonProject1.ServiceReference1.ComprobanteConstatarResponse retVal = ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).ComprobanteConstatar(inValue);
            return retVal.Body.ComprobanteConstatarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobanteConstatarResponse> SBOAddonProject1.ServiceReference1.ServiceSoap.ComprobanteConstatarAsync(SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequest request) {
            return base.Channel.ComprobanteConstatarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobanteConstatarResponse> ComprobanteConstatarAsync(SBOAddonProject1.ServiceReference1.CmpAuthRequest Auth, SBOAddonProject1.ServiceReference1.CmpDatos CmpReq) {
            SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequest inValue = new SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.ComprobanteConstatarRequestBody();
            inValue.Body.Auth = Auth;
            inValue.Body.CmpReq = CmpReq;
            return ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).ComprobanteConstatarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SBOAddonProject1.ServiceReference1.ComprobanteDummyResponse SBOAddonProject1.ServiceReference1.ServiceSoap.ComprobanteDummy(SBOAddonProject1.ServiceReference1.ComprobanteDummyRequest request) {
            return base.Channel.ComprobanteDummy(request);
        }
        
        public SBOAddonProject1.ServiceReference1.DummyResponse ComprobanteDummy() {
            SBOAddonProject1.ServiceReference1.ComprobanteDummyRequest inValue = new SBOAddonProject1.ServiceReference1.ComprobanteDummyRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.ComprobanteDummyRequestBody();
            SBOAddonProject1.ServiceReference1.ComprobanteDummyResponse retVal = ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).ComprobanteDummy(inValue);
            return retVal.Body.ComprobanteDummyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobanteDummyResponse> SBOAddonProject1.ServiceReference1.ServiceSoap.ComprobanteDummyAsync(SBOAddonProject1.ServiceReference1.ComprobanteDummyRequest request) {
            return base.Channel.ComprobanteDummyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SBOAddonProject1.ServiceReference1.ComprobanteDummyResponse> ComprobanteDummyAsync() {
            SBOAddonProject1.ServiceReference1.ComprobanteDummyRequest inValue = new SBOAddonProject1.ServiceReference1.ComprobanteDummyRequest();
            inValue.Body = new SBOAddonProject1.ServiceReference1.ComprobanteDummyRequestBody();
            return ((SBOAddonProject1.ServiceReference1.ServiceSoap)(this)).ComprobanteDummyAsync(inValue);
        }
    }
}
